ARG NODE_VERSION=24
FROM node:${NODE_VERSION}-alpine AS uilayer

WORKDIR /app

# Git is required for some dependencies pulled from repositories
RUN apk add --no-cache git

RUN corepack enable

COPY ./web-app/package.json ./web-app/yarn.lock ./web-app/.yarnrc.yml ./

RUN yarn install

COPY ./web-app .

RUN yarn build

USER node
