default: build-static

yarn-dep:
	@(corepack enable)
	@(yarn install)

build-static:
	@echo "Building frontend static assets to 'build'"
	@if [ -f "${NVM_DIR}/nvm.sh" ]; then \. "${NVM_DIR}/nvm.sh" && nvm install && nvm use; fi && \
	  yarn build

build-static-release:
	@echo "Building frontend static assets to 'build'"
	@if [ -f "${NVM_DIR}/nvm.sh" ]; then \. "${NVM_DIR}/nvm.sh" && nvm install && nvm use; fi && \
	  GENERATE_SOURCEMAP=false yarn build

build-static-istanbul-coverage:
	@echo "Building frontend static assets to 'build'"
	@if [ -f "${NVM_DIR}/nvm.sh" ]; then \. "${NVM_DIR}/nvm.sh" && nvm install && nvm use; fi && \
	  yarn buildistanbulcoverage

test-warnings:
	./check-warnings.sh

test-prettier:
	./check-prettier.sh

find-deadcode:
	./check-deadcode.sh

prettify:
	yarn prettier --write . --log-level warn

pretty: prettify
